(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('arenaCanvas'), ctx=canvas.getContext('2d');
const W=50,H=31,CELL=20,TICK=105,NORMAL_FOODS=3, VERSION='2.1.0';
const COLORS=['#67ef8a','#ff72bd','#63b3ff'], ICONS=['🟢','🩷','🔵'];
const D={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
const CK={arrows:['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'],wasd:['KeyW','KeyS','KeyA','KeyD'],ijkl:['KeyI','KeyK','KeyJ','KeyL']};
const KD={ArrowUp:D.up,ArrowDown:D.down,ArrowLeft:D.left,ArrowRight:D.right,KeyW:D.up,KeyS:D.down,KeyA:D.left,KeyD:D.right,KeyI:D.up,KeyK:D.down,KeyJ:D.left,KeyL:D.right};
let count=2,types=['human','cpu','cpu'],names=['Jhon','Jogador 2','Jogador 3'],controls=['arrows','wasd','ijkl'],show=[true,true,true],showOthers=true,mode='classic',running=false,paused=false,timer=null;
let snakes=[],alive=[],dirs=[],nextDirs=[],foods=[],scores=[],foodsEaten=[],grow=[],respawnAt=[],particles=[],shake=0;
let mission={type:'eat',target:5,progress:0,done:false};
const safe=(s,f)=>String(s||'').trim().replace(/[<>]/g,'').slice(0,14)||f;
const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function label(i){return safe(names[i],`Jogador ${i+1}`)}
function makePlayers(){const box=$('players');box.innerHTML='';for(let i=0;i<count;i++){const d=document.createElement('div');d.className='player';d.innerHTML=`<b style="color:${COLORS[i]}">${ICONS[i]} Jogador ${i+1}</b><select class="select ptype" data-i="${i}"><option value="human">👤 Humano</option><option value="cpu">🤖 CPU</option></select><select class="select pcontrol" data-i="${i}"><option value="arrows">⬆️ Setas</option><option value="wasd">⌨️ W A S D</option><option value="ijkl">🎮 I J K L</option></select><input class="input pname" data-i="${i}" value="${label(i)}" maxlength="14"><label class="check"><input type="checkbox" class="pshow" data-i="${i}" ${show[i]?'checked':''}> Mostrar nome</label></div>`;box.appendChild(d);d.querySelector('.ptype').value=types[i]||'cpu';d.querySelector('.pcontrol').value=controls[i]||['arrows','wasd','ijkl'][i]}}
function syncSettings(){names[0]=safe($('myName').value,'Jhon');show[0]=$('showMe').checked;showOthers=$('showOthers').checked;mode=$('mode').value}
function wall(x,y){return x<0||x>=W||y<0||y>=H}
function reverse(a,b){return a&&b&&a.x===-b.x&&a.y===-b.y}
function occupied(x,y,ignore=-1){for(let i=0;i<count;i++)if(i!==ignore&&alive[i]&&snakes[i]?.some(p=>p.x===x&&p.y===y))return true;return foods.some(f=>f.x===x&&f.y===y)}
function freeCell(){for(let n=0;n<4000;n++){const p={x:Math.floor(Math.random()*W),y:Math.floor(Math.random()*H)};if(!occupied(p.x,p.y))return p}return{x:2,y:2}}
function ensureFoods(){while(foods.filter(f=>f.kind==='normal').length<NORMAL_FOODS){const p=freeCell();foods.push({x:p.x,y:p.y,kind:'normal',value:1})}if(!foods.some(f=>f.kind==='bonus')){const p=freeCell();foods.push({x:p.x,y:p.y,kind:'bonus',value:5})}}
function burst(x,y,color,n=10){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=.5+Math.random()*1.5;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:24+Math.random()*18,color})}}
function spawn(i){const starts=[{x:6,y:7,dx:1,dy:0},{x:43,y:23,dx:-1,dy:0},{x:25,y:26,dx:0,dy:-1}],s=starts[i];let p=occupied(s.x,s.y)?freeCell():s;snakes[i]=[{x:p.x,y:p.y},{x:p.x-s.dx,y:p.y-s.dy},{x:p.x-2*s.dx,y:p.y-2*s.dy}];dirs[i]={x:s.dx,y:s.dy};nextDirs[i]={x:s.dx,y:s.dy};alive[i]=true;grow[i]=0;respawnAt[i]=0;burst(p.x,p.y,COLORS[i],14)}
function reset(){clearInterval(timer);snakes=[];alive=[];dirs=[];nextDirs=[];foods=[];scores=Array(3).fill(0);foodsEaten=Array(3).fill(0);grow=Array(3).fill(0);respawnAt=Array(3).fill(0);particles=[];shake=0;mission={type:'eat',target:5,progress:0,done:false};for(let i=0;i<count;i++)spawn(i);ensureFoods()}
function startGame(){syncSettings();reset();$('menu').classList.add('hidden');$('game').classList.remove('hidden');$('overlay').classList.add('hidden');$('badge').textContent=mode==='turbo'?'⚡ TURBO WORMS':'🏆 CLÁSSICO';running=true;paused=false;buildFeatureHud();render();timer=setInterval(tick,TICK)}
function dropFood(i){for(let n=0;n<foodsEaten[i];n++){const p=freeCell();foods.push({x:p.x,y:p.y,kind:'drop',value:1,owner:i})}}
function kill(i){dropFood(i);const h=snakes[i]?.[0];if(h)burst(h.x,h.y,COLORS[i],24);shake=7;snakes[i]=[];alive[i]=false;scores[i]=0;foodsEaten[i]=0;grow[i]=0;respawnAt[i]=Date.now()+900}
function setDir(i,d){if(alive[i]&&!reverse(dirs[i],d))nextDirs[i]={x:d.x,y:d.y}}
function dangerScore(i,p){if(wall(p.x,p.y))return 10000;for(let j=0;j<count;j++)if(j!==i&&alive[j]&&snakes[j]?.some(q=>q.x===p.x&&q.y===p.y))return 9000;return 0}
function futureRisk(i,d,steps=4){let p={...snakes[i][0]},dir=d,risk=0;for(let k=0;k<steps;k++){p={x:p.x+dir.x,y:p.y+dir.y};risk+=dangerScore(i,p)*(steps-k);for(let j=0;j<count;j++)if(j!==i&&alive[j]&&snakes[j]?.some(q=>q.x===p.x&&q.y===p.y))risk+=5000;const nearWall=Math.min(p.x,W-1-p.x,p.y,H-1-p.y);if(nearWall<2)risk+=120*(3-nearWall);if(k===0){dir=d}}return risk}
function aiDir(i){const h=snakes[i]?.[0];if(!h)return D.right;const targets=foods.filter(f=>['normal','bonus','drop'].includes(f.kind));if(!targets.length)return dirs[i]||D.right;const bonus=foods.find(f=>f.kind==='bonus');let target=targets.slice().sort((a,b)=>dist(h,a)-dist(h,b))[0];if(bonus&&dist(h,bonus)<=18)target=bonus;let best=dirs[i]||D.right,bestScore=-1e9;for(const d of Object.values(D)){if(reverse(dirs[i],d))continue;const p={x:h.x+d.x,y:h.y+d.y};let sc=-dist(p,target);if(target.kind==='bonus')sc+=18;if(target.kind==='drop')sc+=5;if(p.x===target.x&&p.y===target.y)sc+=1000;sc-=futureRisk(i,d,4);if(wall(p.x,p.y))sc-=15000;for(let j=0;j<count;j++)if(j!==i&&alive[j]&&snakes[j]?.[0]&&dist(p,snakes[j][0])<=2)sc-=250;const edge=Math.min(p.x,W-1-p.x,p.y,H-1-p.y);if(edge<2)sc-=120;if(sc>bestScore){bestScore=sc;best=d}}return best}
function nextMission(){const missions=[['eat',5,'🍎 Coma 5 alimentos'],['star',1,'⭐ Pegue 1 estrela'],['survive',45,'⏱️ Sobreviva por 45 segundos'],['score',20,'🏆 Chegue a 20 pontos']];const m=missions[Math.floor(Math.random()*missions.length)];mission={type:m[0],target:m[1],progress:0,done:false,label:m[2],started:Date.now()}}
function updateMission(){if(mission.done)return;if(mission.type==='eat')mission.progress=foodsEaten[0];else if(mission.type==='star')mission.progress=Math.floor(scores[0]/5);else if(mission.type==='score')mission.progress=scores[0];else if(mission.type==='survive')mission.progress=Math.min(mission.target,Math.floor((Date.now()-mission.started)/1000));if(mission.progress>=mission.target){mission.done=true;mission.progress=mission.target}}
function buildFeatureHud(){let hud=document.getElementById('featureHud');if(!hud){hud=document.createElement('div');hud.id='featureHud';hud.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;align-items:center';$('mission').before(hud)}hud.innerHTML=`<div style="background:#0b1220;border:1px solid #293852;border-radius:10px;padding:7px 10px;font-weight:800">${mission.done?'✅':'🎯'} ${mission.label||'Missão'}</div><div style="background:#0b1220;border:1px solid #293852;border-radius:10px;padding:7px 10px">${mission.progress}/${mission.target}</div>`;let mini=document.getElementById('minimap');if(!mini){mini=document.createElement('canvas');mini.id='minimap';mini.width=180;mini.height=112;mini.style.cssText='position:absolute;right:10px;top:10px;width:180px;height:112px;background:rgba(5,9,17,.72);border:1px solid #405575;border-radius:10px;z-index:3;pointer-events:none';$('arena').appendChild(mini)} }
function updateFeatureHud(){const hud=$('featureHud');if(hud){hud.children[0].innerHTML=`${mission.done?'✅':'🎯'} ${mission.label||'Missão'}`;hud.children[1].textContent=`${mission.progress}/${mission.target}`}drawMinimap()}
function drawMinimap(){const m=$('minimap');if(!m)return;const mc=m.getContext('2d');mc.clearRect(0,0,m.width,m.height);mc.fillStyle='#050911';mc.fillRect(0,0,m.width,m.height);const sx=m.width/W,sy=m.height/H;for(const f of foods){mc.fillStyle=f.kind==='bonus'?'#ffd24d':'#ff4f7a';mc.beginPath();mc.arc(f.x*sx+sx/2,f.y*sy+sy/2,f.kind==='bonus'?3:2,0,Math.PI*2);mc.fill()}for(let i=0;i<count;i++)if(alive[i]){mc.fillStyle=COLORS[i];const h=snakes[i][0];mc.beginPath();mc.arc(h.x*sx+sx/2,h.y*sy+sy/2,4,0,Math.PI*2);mc.fill()}}
function tick(){if(!running||paused)return;const now=Date.now();for(let i=0;i<count;i++){if(!alive[i]){if(now>=respawnAt[i])spawn(i);continue}if(types[i]==='cpu')nextDirs[i]=aiDir(i);dirs[i]=nextDirs[i]}
const heads=snakes.map((s,i)=>alive[i]?{x:s[0].x+dirs[i].x,y:s[0].y+dirs[i].y}:null);const die=Array(count).fill(false);for(let i=0;i<count;i++)if(alive[i]){const h=heads[i];if(wall(h.x,h.y))die[i]=true;for(let j=0;j<count;j++)if(i!==j&&alive[j]&&snakes[j].some(p=>p.x===h.x&&p.y===h.y))die[i]=true}
for(let i=0;i<count;i++)if(alive[i]){if(die[i]){kill(i);continue}const h=heads[i];snakes[i].unshift(h);const f=foods.find(q=>q.x===h.x&&q.y===h.y);if(f){scores[i]+=f.value;foodsEaten[i]+=f.value;grow[i]+=f.value;foods.splice(foods.indexOf(f),1);burst(h.x,h.y,f.kind==='bonus'?'#ffd24d':COLORS[i],f.kind==='bonus'?24:12)}if(grow[i]>0)grow[i]--;else snakes[i].pop()}
ensureFoods();updateMission();updateParticles();if(shake>0)shake=Math.max(0,shake-1);render()}
function updateParticles(){particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.03;p.life--});particles=particles.filter(p=>p.life>0)}
function renderScores(){let h='';for(let i=0;i<count;i++)h+=`<div class="score" style="border-color:${COLORS[i]}">${ICONS[i]} <b>${label(i)}</b> • 🍎 ${foodsEaten[i]||0} • ⭐ ${scores[i]||0}${alive[i]?'':' • ☠️'}</div>`;$('scores').innerHTML=h;$('alive').textContent=alive.filter(Boolean).length}
function draw(){ctx.save();ctx.clearRect(0,0,canvas.width,canvas.height);if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#050911';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#0d2038';for(let x=0;x<=W;x++){ctx.beginPath();ctx.moveTo(x*CELL,0);ctx.lineTo(x*CELL,H*CELL);ctx.stroke()}for(let y=0;y<=H;y++){ctx.beginPath();ctx.moveTo(0,y*CELL);ctx.lineTo(W*CELL,y*CELL);ctx.stroke()}const t=Date.now()/180;for(const f of foods){const x=f.x*CELL+10,y=f.y*CELL+10;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';if(f.kind==='bonus'){ctx.font='24px sans-serif';ctx.shadowBlur=12+Math.sin(t)*7;ctx.shadowColor='#ffd24d';ctx.fillText('⭐',x,y)}else{ctx.font='20px sans-serif';ctx.shadowBlur=8;ctx.shadowColor=f.kind==='drop'?(COLORS[f.owner]||'#fff'):'#ff4f7a';ctx.fillText('🍎',x,y)}ctx.restore()}for(let i=0;i<count;i++)if(alive[i]){const s=snakes[i];for(let k=s.length-1;k>=0;k--){const p=s[k];ctx.fillStyle=COLORS[i];ctx.globalAlpha=k===0?1:.82;ctx.beginPath();ctx.roundRect(p.x*CELL+2,p.y*CELL+2,16,16,5);ctx.fill()}ctx.globalAlpha=1;const h=s[0];ctx.fillStyle='#07110b';ctx.beginPath();ctx.arc(h.x*CELL+6,h.y*CELL+6,2,0,Math.PI*2);ctx.arc(h.x*CELL+14,h.y*CELL+6,2,0,Math.PI*2);ctx.fill();if(show[i]&&(i===0||showOthers)){ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText(`${label(i)} • 🍎 ${foodsEaten[i]||0}`,h.x*CELL+10,h.y*CELL-4)}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/40);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*CELL+10,p.y*CELL+10,Math.max(1,p.life/12),0,Math.PI*2);ctx.fill()}ctx.restore()}
function render(){renderScores();updateFeatureHud();draw()}
function handleKey(e){if(!running)return;if(e.code==='KeyP'){paused=!paused;return}if(paused)return;for(let i=0;i<count;i++)if(types[i]==='human'){const keys=CK[controls[i]]||CK.arrows;if(keys.includes(e.code)){e.preventDefault();setDir(i,KD[e.code])}}}
document.addEventListener('keydown',handleKey,{passive:false});
let joyId=null;function joystickMove(e){const r=$('joystick').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,x=e.clientX-cx,y=e.clientY-cy,ax=Math.abs(x),ay=Math.abs(y);if(Math.max(ax,ay)<12)return;setDir(0,ax>ay?(x>0?D.right:D.left):(y>0?D.down:D.up));const max=r.width*.33,m=Math.min(max,Math.hypot(x,y)),a=Math.atan2(y,x);$('stick').style.transform=`translate(${Math.cos(a)*m}px,${Math.sin(a)*m}px)`}
$('joystick').addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;$('joystick').setPointerCapture(joyId);joystickMove(e)});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===joyId){e.preventDefault();joystickMove(e)}});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>$('joystick').addEventListener(ev,()=>{joyId=null;$('stick').style.transform='translate(0,0)'}));
$('start').addEventListener('click',startGame);$('pause').addEventListener('click',()=>paused=!paused);$('restart').addEventListener('click',startGame);$('back').addEventListener('click',()=>{running=false;clearInterval(timer);$('game').classList.add('hidden');$('menu').classList.remove('hidden');renderScores();draw()});$('share').addEventListener('click',async()=>{const url=location.href.split('?')[0];try{if(navigator.share)await navigator.share({title:'Snake Arena',text:'Vem jogar Snake Arena comigo!',url});else{await navigator.clipboard.writeText(url);alert('Link copiado!')}}catch{}});$('refresh').addEventListener('click',()=>location.href=location.pathname+'?v='+VERSION+'&t='+Date.now());$('mode').addEventListener('change',e=>mode=e.target.value);$('count').addEventListener('change',e=>{count=+e.target.value;types=count===3?['human','human','human']:['human','cpu','cpu'];makePlayers()});$('players').addEventListener('change',e=>{const i=+e.target.dataset.i;if(e.target.classList.contains('ptype'))types[i]=e.target.value;if(e.target.classList.contains('pcontrol'))controls[i]=e.target.value;if(e.target.classList.contains('pshow'))show[i]=e.target.checked});$('players').addEventListener('input',e=>{if(e.target.classList.contains('pname'))names[+e.target.dataset.i]=safe(e.target.value,`Jogador ${+e.target.dataset.i+1}`)});$('myName').addEventListener('input',e=>names[0]=safe(e.target.value,'Jhon'));
makePlayers();nextMission();render();
})();