const __V = (await import('fs')).readFileSync(new URL('../version.txt', import.meta.url), 'utf8').trim(); // versão ATUAL: estes testes tinham o número da época escrito à mão e quebravam a cada versão nova
// Testes estruturais da escolha da inimiga, zonas e Loja.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { novoRelatorio } from './_ambiente.mjs';
const raiz=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const ler=p=>fs.readFileSync(path.join(raiz,p),'utf8');
const relatorio=novoRelatorio();
const index=ler('index.html'),state=ler('js/state.js'),loop=ler('js/loop_stable_336.js'),render=ler('js/render_stable_341.js'),prog=ler('js/progression.js'),players=ler('js/players.js');
relatorio.secao('Inimiga');
relatorio.check('Escolha da inimiga no início',index.includes('id="hunterEnabledStart"'));
relatorio.check('3 zonas',loop.includes('const HUNTER_ZONE_COUNT = 3'));
relatorio.check('3 segundos por zona',loop.includes('const HUNTER_ZONE_HOLD_MS = 3000'));
relatorio.check('Zonas ficam no estado',state.includes('hunterZones')&&state.includes('hunterZoneCompleted'));
relatorio.check('Zonas sincronizadas online',loop.includes('hunterZones: state.hunterZones')&&loop.includes('hunterZoneCompleted: state.hunterZoneCompleted'));
relatorio.check('Zonas desenhadas',render.includes('function drawHunterZones')&&render.includes('drawHunterZones();'));
relatorio.secao('Loja');
relatorio.check('Catálogo de mapas',prog.includes('export const SHOP_MAPS'));
relatorio.check('Catálogo de fantasias',prog.includes('export const SHOP_SKINS'));
relatorio.check('Compra de mapas',prog.includes('export function buyMap'));
relatorio.check('Compra de fantasias',prog.includes('export function buySkin'));
relatorio.check('Persistência de mapas',prog.includes('unlockedMaps:[]'));
relatorio.check('Persistência de fantasias',prog.includes('unlockedSkins:[]'));
relatorio.check('Botão da loja existe',prog.includes('function shopButton'));
relatorio.check('Loja aparece no progresso',index.includes('data-progress-section="shop"')&&index.includes('data-progress-panel="shop"'));
relatorio.check('Mapas premium bloqueados no seletor',index.includes('data-shop-map="cyber"'));
relatorio.check('Fantasias premium bloqueadas na personalização',players.includes('isSkinUnlocked')&&players.includes('disabled'));
relatorio.secao('Versão');
relatorio.check('Versão 4.2.2',ler('version.txt').trim()===__V);
relatorio.check('Cache 4.2.2',ler('sw.js').includes('snake-arena-v'+__V));
relatorio.fim();
